### ISSUE TITLE
Allow download to be run without setting up database configuration

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/kingfisher#167]
**User story:**

> **As a** third party application builder **I want to** be able to use ocdsdata to *download* full or sample data from any known publishers **so that** I can import it into my own toolchain. 

I was just trying to do this, and found it wasn't terribly intuitive because:

* (a) I had to set-up a configuration file for database access, even though I didn't want to use a database;
* (b) I had to run gather, and then fetch steps, rather than having a simple 'download' command which would get files for me;
* (c) I had to look at the source code to find out which countries data was available;

How complex would it be to:

* Add a `download` command (alongside 'run') that would gather and fetch into the 'data' directly without needing databaset set-up, and manually running gather and fetch. (this should support the --sample flag) 
* Add a `list` command which would provide a list of all current available sources of data, ideally with name, URI/URI pattern, and any important notes that might exist in the scraper

We have organisations wanting to work with OCDS data who I think could find this very useful.

**Comment by jpmckinney** [comment]
What would happen if you ran the command with `--ignorestore` and `--ignorecheck`? This would run gather and fetch in one command. Would it still complain about requiring database access? If those steps are skipped, I don't think the CLI should complain, because gather and fetch shouldn't be interacting with the database (only with the metadata database, which is a SQLite file).

Instead of a new `download` command, I propose some interface changes to the run command in #170 (and #169), such that a user should be able to run, e.g. `ocdsdata-cli run --only gather fetch <source>`. If we add an example to the readme showing how to download data, I think we can avoid more complex solutions like making a `--only download` option that is translated to `--only gather fetch`, or making an entirely new command.

A `list` command is a good idea and may interact with #164.

**Comment by jpmckinney** [comment]
I see `ocdsdata/maindatabase/config` is always run (therefore ocdsdata-cli always complains about database access if there's no config file or environment variable). Created #171.

**Comment by odscjames** [comment]
Thanks for the report Tim and sorry for the troubles!

I am at a conference this week so I can't look at this fully now.

However I totally agree that #171 is a bug that should be fixed.

On the other issues (and I see CLI options are being discussed elsewhere too) I agree these could do with looking at and I will comment on those soon.

**Comment by odscjames** [comment]
The split into 2 parts in the new system solves this; now people who just want to get the files use LHS/Scrape only and totally ignore RHS/Process. Closing.
