### ISSUE TITLE
User story: As a helpdesk analyst I want to load local files into the database so I can provide feedback on a dataset

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher#173]
Sometimes publishers may share bulk files with the helpdesk for feedback before they are published online at a URL. I would like to be able to load local files into ocdsdata so I can use existing queries and templates to provide feedback on the data.

@kindly wrote [this scraper](https://gist.github.com/kindly/b0a363a7d7bd4a32e2ed4b43b75354fd) to load the draft data from Georgia into the database, it would be good to have a generic way of doing this in the command line tool, e.g. by providing the name of the source, the type of file being loaded (release package, record package etc.) and the path to the local files.

**Comment by odscjames** [comment]
Ok, so thinking about this:

I think the way to do this is have a new source "LocalLoad". 

This would be flagged so new instances of this could not be created the normal way. This flag would also make sure "run --all" still worked - it would run all the rest and ignore this one.

Instead, to create a new one you would run a new sub command, passing it the directory that contains the local files.

A new run would be created, and the files copied in. The metadatabase would be set up to look like the gather and fetch stages had happened, but not any later stages (store, check).

One complication is that for each file we need,
 - encoding - we can default this to utf-8 and have CLI options.
 - type - record_package, release_package, record_package_list, release_package_list, record_package_list_in_results, etc. Have CLI options to say in simple cases, all these files are "x" type? For now, ignore the more complex case when the directory contains more than one type?

A normal run command could then be issued that would allow the other stages to work (store, check).

How does that sound?

Note copying the files is good because it then creates separation between the original sources and the ones we work with - note util.save_content removes control codes, and maybe we'll want to do the same here later. It's bad in that for really big loads, you need more disk space. But we'll deal with that later.

**Comment by duncandewhurst** [comment]
Thanks James. With the caveat that I don't really know anything about how the pipeline has been implemented, that sounds good to me.

> type - record_package, release_package, record_package_list, release_package_list, record_package_list_in_results, etc. Have CLI options to say in simple cases, all these files are "x" type? For now, ignore the more complex case when the directory contains more than one type?

Bulk files should be either single or multiple (i.e. segmented) release or record packages, so those two should be the main options. I think in cases where the files aren't release or record packages (e.g. a list of releases) the analyst should be able to massage them into the right format before loading them into the database and will need to set the version and any extensions in the package metadata anyway, so probably best done outside of the tool.

I don't expect we'd have a mixture of types to load in, so setting one type for the whole load should be fine.

**Comment by jpmckinney** [comment]
Sounds good to me. If the new special source can get away with implementing `gather_all_download_urls` to return [`file://` URIs](https://en.wikipedia.org/wiki/File_URI_scheme), and either re-implementing or changing the implementations of `save_url` or `save_content` to copy files if the file URI scheme is used, and that might be a tidy solution. The part of `save_content` that cleans control characters should probably be refactored into its own method, so that `save_content` has fewer responsibilities.

**Comment by odscjames** [comment]
Done in new system, closing
