### ISSUE TITLE
Add records from Uruguay

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher#205]
Uruguay has this service: http://www.comprasestatales.gub.uy/ocds/record/idcompra that has records with all the links to the releases for a given contracting id (the first numbers in the release id)

**Comment by odscjames** [comment]
I have merged in the pull request - Thank You - but I will leave this issue open and I will try and look at it later.

The source is doing a lot of queries in the gather stage, and it would be better to move them to the fetch stage. This is because the gather stage will not resume if it breaks half way through, but the fetch stage will. 

The Data Type "meta" can be used here, with the gather stage returning the URL of the first page only and the fetch stage then looking for the "meta" type and adding the next page, and data URLs. The priority flag can be used to get all the list pages before data URLs, so the status command returns an accurate total count as soon as possible. See Australia for an example.

**Comment by yolile** [comment]
Uruguay has now a service to get the releases given a year and month: http://comprasestatales.gub.uy/ocds/rss/AAAA/MM
from 2017/12 til now
we have to update the script to call to this API

**Comment by odscjames** [comment]
After pull request #242, are we happy with this and can this be closed?

(I just tried http://comprasestatales.gub.uy/ocds/rss/2017/01 and got a 404! Anything before http://comprasestatales.gub.uy/ocds/rss/2017/11 gives me a 404?)

**Comment by yolile** [comment]
> After pull request #242, are we happy with this and can this be closed?

Yes

> (I just tried http://comprasestatales.gub.uy/ocds/rss/2017/01 and got a 404! Anything before http://comprasestatales.gub.uy/ocds/rss/2017/11 gives me a 404?)

Yes, the service respond from 2017/12 onwards
