### ISSUE TITLE
Wrong handling of errors in json

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher#241]
In:

https://github.com/open-contracting/kingfisher/blob/22b60187b0d3915d8a61f4a34a528bed0702e181/ocdskingfisher/base.py#L261-L283

the line `if 'releases' not in json_data: ` asks for 'releases' path but then just used it in line 270 
`data_list = json_data['releases']`
  generating an exception without reporting wich file has problems, because **error_msg** is ignored.

**Comment by odscjames** [comment]
Thank you for this!

Currently if any exception happens in store, the whole process stops. This is not good.

It would be good to move to a model where this is done on a per file basis - so if one file errors while storing, it will still try and store the rest. What do you think?

- Table collection_file_status - add JSONB column "errors" (like warnings column) and add "store_error_at"
- Change base class , run_store loop - so that if any errors for a file we put error message in db and move on to next file. (Probably make a new function run_store_for_file that can throw exceptions freely, and run_store will do the file loop and catch exceptions)
- Make sure we call database.end_store(source_session_id) only if no errors occurred - check "store_error_at" column.

This will mean we can't move from store to check stage until all errors fixed - but that's currently true for the fetch to store stage, so it's following an existing pattern. At least we will have all the rest of the files stored, and we will have a clear error for the files that are causing problems! (This is also like the fetch stage.) We can sort that out later, both stages at the same time.

Also, where did you see this? It will help test this. I've seen something like this in https://github.com/open-contracting/kingfisher/issues/207#issuecomment-420312300 but the use of JSON Lines complicates things there.

**Comment by jpmckinney** [comment]
@odscjames Your comment seems very much in line with mine at https://github.com/open-contracting/kingfisher/issues/197#issuecomment-420723114

However, I think rather than adding file-specific methods like `run_store_for_file` to `Source`, I think it's better to encapsulate such methods in a new class (like `File` or `Resource`).

**Comment by jpmckinney** [comment]
Sounds reasonable!

**Comment by jpmckinney** [comment]
Is this bug fixed in kingfisher-scrape?

**Comment by jpmckinney** [comment]
@odscjames @yolile Is this bug fixed in either kingfisher-scrape or kingfisher-process?

**Comment by jpmckinney** [comment]
Yes, it's fixed (kingfisher-process raises an error right away instead of setting `error_msg`)
