### ISSUE TITLE
Decide on an architecture for the conversion/transformation framework

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#269]

**Comment by jpmckinney** [comment]
See my proposal here for a general direction, that avoids either creating our own ETL framework, or bending an existing ETL framework to our needs. Further up on the page, I have notes on ETL frameworks I'd looked at: https://docs.google.com/document/d/1zeBhhSV9eLPoRu8cIy-0y4HNT02fCXNr3b6LdtyijVM/edit#heading=h.x8e0xcgkd6oz

**Comment by duncandewhurst** [comment]
From a perspective of keeping Kingfisher user friendly I prefer to minimise the number of different tools and cli commands that need to be used to get data into the database.

From a helpdesk perspective, in line with recent discussions in crm issue #4055 on user friendly tooling for conversion to spreadsheets and other helpdesk interactions with potential kingfisher users who are not developers (e.g. TI Health project, BBC journalists etc.), I think we should design to maximise ease of use for a less technical audience even at the cost of more complex code for us to maintain.

cc @juanpane @yolile

**Comment by odscjames** [comment]
Yesterday I had a chat with @kindly about this, and a shorter chat with @duncandewhurst to clear up a point after that. I'm putting up my rough notes here - they probably don't make total sense to others, but I won't have time to get to this till after the holidays so it should be noted.

Collections have current unique ID's (source, date, sample)
Add another element to this ( ....., transform)

Make sure they can be chained - Describe them as (from collection_id, transform) probably?

Note transform has 2 types;
* can run straight away on a partial collection e.g. 1.0 to 1.1
* must wait till we get all data before starting e.g. compile releases

Each transform has it's own status table to track how through it is, as they will be different for each of the two cases, and maybe different for different transforms. But put output back to usual tables

As well as release & record have compiled_release - these are different enough that they must be different.

Reports are not releases! Reports will have different tables for output. (as checks already do)

After discussing an issue with David, I clarified with Ducan. He says - options on everything, on by default.

**Comment by jpmckinney** [comment]
I think we're all agreed on wanting tools to be user-friendly. I think the only disagreement is in how to do that.

> From a perspective of keeping Kingfisher user friendly I prefer to minimise the number of different tools and cli commands that need to be used to get data into the database.

See https://github.com/open-contracting/kingfisher/issues/272#issuecomment-448737791 For the helpdesk use case, it will be one command. A similar approach can be taken for other use cases.

Regarding 4055, what I hear is that some users don't want to have to install command-line tools that aren't already on their system, and some users don't want to use command-line tools at all. So, that's *interface* feedback. They are not saying, "give me an all-in-one tool"; they are saying they want a different interface. For that issue, the interface might be the Data Review Tool, or a stand-alone tool (it depends on what they are using Flatten Tool and OCDS Kit for). Let's keep that discussion to the CRM.

**Comment by jpmckinney** [comment]
@odscjames Regarding defaults and @duncandewhurst's comment: the defaults should be minimal. We can have a configuration file (or environment variables) on our server, such that, to a helpdesk analyst, it would behave as though the defaults were what they wanted. However, we should not set the defaults in the code to be the helpdesk use case (e.g. having 1.1 upgrade and compiled releases 'on' by default). We don't know enough about others' use cases to judge whether this is a sensible default (i.e one that only exceptional users wouldn't want) or not. So, for now, it's better to be conservative with our defaults.

Otherwise, I think we're broadly on the same page. I think it's fine to run transformations within Kingfisher – though we should still support the type of usage described in the linked document, where as user might want to follow a different path than the helpdesk analysts do.

If I understand your notes, I think it makes sense for each transformation to result in a new collection. (If it turns out we rarely want the original collection, we might make it an option to delete the original collection once it's fully transformed.)

**Comment by robredpath** [comment]
@odscjames @kindly can you let me know the decision on how to do this?

**Comment by odscjames** [comment]
Req 2.1 has now been basically done. We followed what we agreed at the top of this thread. This also lays the groundwork for Req 2.2.

**Comment by jpmckinney** [comment]
We have one now, so closing.
