### ISSUE TITLE
[1.1] [SPIKE - 3 days] Familiarisation with Scrapy + scrapyd deployment

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#273]

**Comment by jpmckinney** [comment]
As part of this, let's check if there are any popular scrapy web UIs besides scrapyd, and share the results of that check in this issue.

**Comment by rhiaro** [comment]
This scrapyd web UI looks new, active, and shiny: https://github.com/my8100/scrapydweb (usual caveats: one developer, not official Scrapy code, so long-term maintenance and who it's currently used by uncertain).

Screenshots of this one look nice: https://github.com/DormyMo/SpiderKeeper. More contributors but less recent activity. Doesn't support individual scraper stats yet.

This is a fork of the previous one, *with* individual scraper stats, and lots of pretty charts: https://github.com/fliot/ScrapyKeeper

This one is simpler, more of a nice skin over existing functionality. No individual crawler stats: https://github.com/jxltom/scrapymon

**Comment by jpmckinney** [comment]
Do we have a list of requirements for the UI?

If the list of requirements is short, simple and stable over time, then the main concern is whether the project stays up-to-date with its requirements (mainly with Scrapy). Otherwise, it's fine for a functional UI to have low activity.

How big are the codebases? If they are small, then it's easier to maintain a fork if needed.

**Comment by robredpath** [comment]
@BibianaC to review @rhiaro 's deploy instructions as part of this

**Comment by jpmckinney** [comment]
"Familiarisation with Scrapy + scrapyd deployment" seems complete, though there might be follow-up issues.
