### ISSUE TITLE
Decide on how we transform from raw to normalised state

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#85]
We know what the raw state looks like. 

We (broadly) know what the normalised state looks like, and the algorithmic process for getting there (correct me if I'm wrong on this, @kindly?)

We had originally talked about using SQL to do the transformation, but since Julia's left we don't have so much SQL expertise or preference for using SQL. Other options include doing the processing in pure Python, or using a framework such as pandas.

In the first few days of the sprint (or even before we start, if people have time to start the discussion here), we should decide on how we go about doing this transformation. 

cc: @juanpane @Tim0th1 who may well have opinions here.

**Comment by timgdavies** [comment]
I understood that this code was potentially useful for some of our statistics generation, if not our normalisation into tables: https://kindly.github.io/notebooks/ocds/coverage_ocds 

I've been exploring querying JSON with PostGres, and understand that we should be able to do lots of what we need in SQL - and that the key question for normalisation is how normalised we need to be in order to have performance on querying.

**Comment by robredpath** [comment]
Thanks, @timgdavies . One factor we should consider in our choice of tech is maintainability - where the code will sit, who will see it as approachable vs who will see it as a 'black box', and how confident everyone who needs to use it will be in modifying it. 

If we're happy that we can skill everyone up sufficiently to be able to use SQL for this (and I'm not expecting it to be particularly challenging SQL) then this could be a very easy discussion. But, I remember how hard I found learning SQL, sets and relations coming from a procedural programming background, so I want to consider how others will find this.

**Comment by Tim0th1** [comment]
This seems like a **very** important conversation. 
I think minimising SQL use is not easy but it may be desirable for the promotion of OCDS.

My perception is that python is growing so fast and is so popular that it would be more attractive to enable this type of transformation solution. 

In the past, my SQL weakness could be fudged by only using a little at the beginning of the pipeline but then I'd read the data to a pandas dataframe. However, I never stepped outside a 2gb database before. OCDS is much bigger isn't it? I take that to be the key normalisation constraint.

If we are just looking at an interim solution it may not matter too much. Otherwise, my view is that we need to undertake some end user research for accessibility. What will they teach in classrooms? Every social science undergraduate will learn python but not SQL. We want to maximise accessibility.

Crudely, I suppose I see a compromise as a really simple bespoke microsoft Access type UI for the SQL data fetch linked to a Jupyter book reading the set of related output tables in a pandas dataframe.

**Comment by odscjames** [comment]
I don't have a strong preference either way but to add a few notes:

1) The raw tables have some stuff to try and avoid storing duplicated data when importing the same source across different time points, and we should try and do the same for normalised tables.

2) To build on Rob's "choice of tech is maintainability" point, I'd strongly push for automated tests what ever solution we go for. I think it should be possible in either case. Ideally, we'd get to the point where a lot of people can treat this bit as essentially a black box, and because of the tests they would just have confidence that it works. (This also lets us change bits around later while having confidence we haven't broken it!)

3) We learnt during the community call that the choice of Postgresql wasn't universally liked, so maybe there is something to be said for keeping this in Python as much as possible and thus making it easier for others to adopt to other data stores?

>We (broadly) know what the normalised state looks like, and the algorithmic process for getting there (correct me if I'm wrong on this, 

Think that is slightly wrong.

> and that the key question for normalisation is how normalised we need to be in order to have performance on querying.

I actually think this is the first question we really need to tackle - it's a big question, and once we have the answer to that we can discuss how to get from A->B. At the moment, it might be the case that B isn't totally defined clearly.

**Comment by timgdavies** [comment]
I've been doing some testing with sample data to get a sense of (a) how to query the current data; (b) what we can do with JSON queries in postgres; (c) what issues we will hit in terms of coming up with normalised versions of the data (the big issues come when you try and combine two arrays in a single table, and you have to make choices about repeating of rows in data-frame representations. 

So far, I've been looking at queries to get the latest version of data for a given publisher, which I think means I need to join quite a few tables:


```sql
SELECT data 
FROM data 
LEFT JOIN release on release.data_id = data.id 
LEFT JOIN source_session_file_status on release.source_session_file_status_id = source_session_file_status.id
LEFT JOIN source_session on source_session_file_status.source_session_id = source_session.id 
WHERE source_session.id IN (SELECT id FROM source_session WHERE source_id = '{{source}}' ORDER BY data_version DESC LIMIT 1)
```

I've then been looking at how this performs if I use the Postgres JSON features to pull out things like 'tenders', 'awards' etc.

```sql
SELECT data, data -> 'tender' as tender, data->'awards' as awards  
FROM data 
LEFT JOIN release on release.data_id = data.id 
LEFT JOIN source_session_file_status on release.source_session_file_status_id = source_session_file_status.id
LEFT JOIN source_session on source_session_file_status.source_session_id = source_session.id 
WHERE source_session.id IN (SELECT id FROM source_session WHERE source_id = '{{source}}' ORDER BY data_version DESC LIMIT 1)
```

This seemed to get much slower than without the JSON queries, suggesting (initially) that some pre-normalisation of the JSON content could make sense?

**Comment by timgdavies** [comment]
I've been doing a bit more testing of postgres JSON query, and finding the combination of postgres + redash's JSON output option is really rather awesome. 

The `jsonb_array_elements` function seemed to perform very well, and exactly as I wanted in the query below, to create a row for each item/item classification. 

![image](https://user-images.githubusercontent.com/342624/41063663-2b989af4-69d1-11e8-8d43-f778fb00c2e3.png)

The query used was:

```sql
SELECT  data, 
        data -> 'ocid',
        data -> 'buyer' as buyer,
        data -> 'planning' as planning,
        data -> 'tender' as tender,
        data -> 'tender' -> 'items' as tender_items,
        jsonb_array_elements(data -> 'tender' -> 'items')->'classification'->'scheme' as tender_items_classification_scheme,
        jsonb_array_elements(data -> 'tender' -> 'items')->'classification'->'description' as tender_items_classification_description ,
        jsonb_array_elements(data -> 'tender' -> 'items')->'classification'->'id' as tender_items_classification_id,
        data -> 'awards' as awards,
        data -> 'contracts' as contracts
FROM data 
LEFT JOIN release on release.data_id = data.id 
LEFT JOIN source_session_file_status on release.source_session_file_status_id = source_session_file_status.id
LEFT JOIN source_session on source_session_file_status.source_session_id = source_session.id 
WHERE source_session.id IN (SELECT id FROM source_session WHERE source_id = '{{source}}' ORDER BY data_version DESC LIMIT 1)
```

where {{source}} was 'uk_contracts_finder'

**Comment by robredpath** [comment]
We talked about this at length in sprint prep on Friday. The fundamental shift in my thinking during the discussion has been that this isn't necessarily about us developing a single piece of code (be it SQL, Python, or anything else) that spits out normalised tables at the end, but helping make sure that the analysts who are using the data have the tools that they need to do their work, which may or may not include normalised tables, or stock queries, or helper tables....etc. 

So, this is great to see @timgdavies - and I think that rather than aiming for a period of user research followed by development and then handover, an ongoing conversation and support around what's useful would be the way forward - eg in internal issue 15228 I'm helping Duncan get some specific historic data, and if that proves to be something we want to do repeatedly I can look at adding it as a function to the cmdline tool. Here, we've already got a ticket to work next sprint around helping people store and share useful queries, and if some regular preprocessing helps then we can add that to the tool.

**Comment by timgdavies** [comment]
Agreed @robredpath. I think saved and parameterised queries in redash could get us quite a long way here.

And if we get permissions set-up right in both Redash and Postgres, then could be possible to use front-end interface to run some on demand / scheduled queries to create those helper tables.

**Comment by timgdavies** [comment]
A quick note that one of the most important steps for us analysing the data though is converting from 1.0 -> 1.1, which may need to happen in python. 

Without this, we end up having to write queries that search in multiple places for 1.0 and 1.1 data. Whereas ideally we would like to know:

* Who originally published as 1.0;
* **What** people are publishing whether they used 1.0 or 1.1;

The main thing here is about the `parties` section (which was introduced in 1.1, and which 1.0 data can be programatically translated into). 

We should be aware in anything we architect that, whilst conversion from 1.x -> 1.x+1 should always be possible, in future we may have both 1.x and 2.x data in a database, and these may not be compatible with one another. 

One possible way to handle things may be to have separate tables for each data version, or just a version flag in the data table.

Note that where no version is given, we should assume version is 1.0 (this is CoVEs behaviour too)

**Comment by robredpath** [comment]
@timgdavies now that's really interesting. Why do you need to do that conversion?

**Comment by timgdavies** [comment]
The main issue is this one:

> Without this, we end up having to write queries that search in multiple places for 1.0 and 1.1 data. 

In the BigQuery workflow we were already doing this using the following script: https://github.com/open-contracting/sample-data/blob/master/real-examples/update_to_v1_1.py

It really helps to promote just one way of querying on parties.

In general, we would encourage anyone building OCDS tools to target the latest version of the schema, and 'upgrade' any incoming data in earlier versions when loading it.

**Comment by robredpath** [comment]
Thanks @timgdavies , that's really helpful!

**Comment by jpmckinney** [comment]
Re: Upgrade from 1.0 to 1.1, see #256

**Comment by jpmckinney** [comment]
Re: Compile releases, see #133 

My understanding is that this issue was originally about whether to transform the JSON into flat SQL tables. It seems there has been no demand for that, but rather for transformations of the JSON into other JSON. The latter is covered in linked issues, so closing.
