### ISSUE TITLE
Install redash and pgadmin

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher#92]
It may be better to just connect to hosted redash, depending on performance for large data sets.

**Comment by odscjames** [comment]
I have been working on Redash, and unfortunately hit problems. Basically, Redash's install script is made for Ubuntu 16. I tested it on several Ubuntu 18 VM's and it seemed fine so we went ahead. But it turns out for some reason "python" is "python2" on my test VM's and "python" is "python3" on the live server. The redash install script expects python2, so it broke on live.

So there are several options here:

  *  try and bodge an install by changing or mapping the default python temporarily. I'm not to keen to do this - there may be other issues and the whole "install by running a script" isn't great anyway. It kind of takes over and assumes it can install a lot of stuff. This was just about ok when I thought it worked, but i'm not to keen if there is a lot of stuff we have to hack.  
  *  install Redash on it's own server, Ubuntu 16. (2GB) This could then be a general redash server (if we have other uses for it). It then doesn't matter what the install scripts do, as there is nothing else on that server to conflict with.
  *  there is also a docker option. Run docker on ocdsdata server, install via that. We would have to do some work to make sure we could do things like backup the postgresql DB if we did this. (We have to do that with the last 2 options to, but it's easy to see how to do that and I'm not sure how their Docker scripts are configured).
  *  use their hosted version - it starts at $49/month.

End of day here, so this is just a write up. I will consider options.

**Comment by robredpath** [comment]
@odscjames thanks for your work on this. Installing it on its own server seems like a reasonable option - do you have a sense of a resources required? I'd be happy for us to consider a Docker option, but only if we're confident that it's sufficiently well-understood for us to be able to maintain it. 

Having looked at the install script, it looks like it'd be relatively straightforward to make it work - just working through it step-by-step on a sufficiently rebuildable machine. We could even then contribute it back to upstream! But, that's definitely more work than just spinning up a box for this on 16.04.

**Comment by odscjames** [comment]
> Having looked at the install script, it looks like it'd be relatively straightforward to make it work

True, but there is also the issue of making sure the upgrade script works too, so this is something we'd need upstream support on.

I'll just set this up on it's own machine for now.

2GB is the spec I've seen. https://discuss.redash.io/t/recommended-minimum-server-requirements/884

**Comment by odscjames** [comment]
redash is now installed. I will post more details in the OC CRM rather than here (for obvious reasons) and this issue can move on to us looking at pgadmin.

**Comment by odscjames** [comment]
It's been pointed out that we should do SSL on this.

**Comment by jpmckinney** [comment]
Is pgadmin still needed? Can this issue be closed?

**Comment by jpmckinney** [comment]
Closing as can be re-opened if there is demand.
